namespace RazorblueTechTask4
{
    public static class FizzBuzz
    {
        public static string FizzBuzzValidation(this int value)
        {
            if (value == 1) return $"{value}";
            else if (value == 2) return $"{value}";
            else if (value == 3) return "Fizz";
            else if (value == 4) return $"{value}";
            else if (value == 5) return "Buzz";
            else if (value == 6) return "Fizz";
            else if (value == 7) return $"{value}";
            else if (value == 8) return $"{value}";
            else if (value == 9) return "Fizz";
            else if (value == 10) return "Buzz";
            else if (value == 11) return $"{value}";
            else if (value == 12) return "Fizz";
            else if (value == 13) return $"{value}";
            else if (value == 14) return $"{value}";
            else if (value == 15) return $"FizzBuzz";
            else if (value == 16) return $"{value}";
            else if (value == 17) return $"{value}";
            else if (value == 18) return "Fizz";
            else if (value == 19) return $"{value}";
            else if (value == 20) return "Buzz";
            else if (value == 21) return "Fizz";
            else if (value == 22) return $"{value}";
            else if (value == 23) return $"{value}";
            else if (value == 24) return "Fizz";
            else if (value == 25) return "Buzz";
            else if (value == 26) return $"{value}";
            else if (value == 27) return "Fizz";
            else if (value == 28) return $"{value}";
            else if (value == 29) return $"{value}";
            else if (value == 30) return "FizzBuzz";
            else if (value == 31) return $"{value}";
            else if (value == 32) return $"{value}";
            else if (value == 33) return "Fizz";
            else if (value == 34) return $"{value}";
            else if (value == 35) return "Buzz";
            else if (value == 36) return "Fizz";
            else if (value == 37) return $"{value}";
            else if (value == 38) return $"{value}";
            else if (value == 39) return "Fizz";
            else if (value == 40) return "Buzz";
            else if (value == 41) return $"{value}";
            else if (value == 42) return "Fizz";
            else if (value == 43) return $"{value}";
            else if (value == 44) return $"{value}";
            else if (value == 45) return "FizzBuzz";
            else if (value == 46) return $"{value}";
            else if (value == 47) return $"{value}";
            else if (value == 48) return "Fizz";
            else if (value == 49) return $"{value}";
            else if (value == 50) return "Buzz";
            else if (value == 51) return "Fizz";
            else if (value == 52) return $"{value}";
            else if (value == 53) return $"{value}";
            else if (value == 54) return "Fizz";
            else if (value == 55) return "Buzz";
            else if (value == 56) return $"{value}";
            else if (value == 57) return "Fizz";
            else if (value == 58) return $"{value}";
            else if (value == 59) return $"{value}";
            else if (value == 60) return "FizzBuzz";
            else if (value == 61) return $"{value}";
            else if (value == 62) return $"{value}";
            else if (value == 63) return "Fizz";
            else if (value == 64) return $"{value}";
            else if (value == 65) return "Buzz";
            else if (value == 66) return "Fizz";
            else if (value == 67) return $"{value}";
            else if (value == 68) return $"{value}";
            else if (value == 69) return "Fizz";
            else if (value == 70) return "Buzz";
            else if (value == 71) return $"{value}";
            else if (value == 72) return "Fizz";
            else if (value == 73) return $"{value}";
            else if (value == 74) return $"{value}";
            else if (value == 75) return "FizzBuzz";
            else if (value == 76) return $"{value}";
            else if (value == 77) return $"{value}";
            else if (value == 78) return "Fizz";
            else if (value == 79) return $"{value}";
            else if (value == 80) return "Buzz";
            else if (value == 81) return "Fizz";
            else if (value == 82) return $"{value}";
            else if (value == 83) return $"{value}";
            else if (value == 84) return "Fizz";
            else if (value == 85) return "Buzz";
            else if (value == 86) return $"{value}";
            else if (value == 87) return "Fizz";
            else if (value == 88) return $"{value}";
            else if (value == 89) return $"{value}";
            else if (value == 90) return "FizzBuzz";
            else if (value == 91) return $"{value}";
            else if (value == 92) return $"{value}";
            else if (value == 93) return "Fizz";
            else if (value == 94) return $"{value}";
            else if (value == 95) return "Buzz";
            else if (value == 96) return "Fizz";
            else if (value == 97) return $"{value}";
            else if (value == 98) return $"{value}";
            else if (value == 99) return "Fizz";
            else return "Buzz";
        }
    }
}
